### ISSUE TITLE
Refonte/Correction de typo...../Bug

### ISSUE THREAD

**Issue by JJeanniard** [kyweez/CDA-RESSOURCES#94]
- [ ] Correction de typo ticket #93 
- [ ] Continuous integration ticket #47 
 - [ ] Application du marketplace Github et leurs utilities #38 
 - [ ] 
- [ ]  Gestion de Projet ticket #2 
* Chapitre qui est absente
